import type { Alert, AppState, Offer, Reservation, Shop } from "./types";
import { todayEndOfDayISO } from "./utils";

const ZONE = { city: "Villeneuve", zip: "1844" };

export function createSeedShops(): Shop[] {
  const trial = new Date();
  trial.setDate(trial.getDate() + 25);
  const trialEndsAt = trial.toISOString();

  return [
    {
      id: "shop_dasilva",
      name: "Épicerie Da Silva",
      slug: "da-silva",
      category: "epicerie",
      address: "Rue des Narcisses 3",
      phone: "021 960 36 28",
      ...ZONE,
      lat: 46.3972,
      lng: 6.9265,
      description: "Épicerie de quartier — produits frais et portugais.",
      openUntil: "19:00",
      published: true,
      devicePlan: "telephone",
      trialEndsAt,
      emoji: "",
      color: "#2E7D32",
    },
    {
      id: "shop_vracshop",
      name: "Vracshop",
      slug: "vracshop",
      category: "epicerie",
      address: "Grand-Rue 84",
      phone: "021 968 11 53",
      ...ZONE,
      lat: 46.3968,
      lng: 6.9251,
      description: "Vrac, bio et zéro déchet au centre-ville.",
      openUntil: "18:30",
      published: true,
      devicePlan: "tablette",
      trialEndsAt,
      emoji: "",
      color: "#43A047",
    },
    {
      id: "shop_macheret",
      name: "Macheret Fromage",
      slug: "macheret",
      category: "cremiere",
      address: "Grand-Rue 21",
      phone: "021 960 13 75",
      ...ZONE,
      lat: 46.3975,
      lng: 6.9248,
      description: "Crémière et fromages locaux depuis des générations.",
      openUntil: "18:00",
      published: true,
      devicePlan: "telephone",
      trialEndsAt,
      emoji: "",
      color: "#F9A825",
    },
    {
      id: "shop_durgnat",
      name: "Boulangerie Durgnat",
      slug: "durgnat",
      category: "boulangerie",
      address: "Grand-Rue 61",
      phone: "021 960 20 10",
      ...ZONE,
      lat: 46.3965,
      lng: 6.9258,
      description: "Pains au levain, viennoiseries et pâtisseries du jour.",
      openUntil: "18:30",
      published: true,
      devicePlan: "telephone",
      trialEndsAt,
      emoji: "",
      color: "#D4A017",
    },
    {
      id: "shop_fontaine",
      name: "Boucherie de la Fontaine",
      slug: "fontaine",
      category: "autre",
      address: "Rue des Remparts 2",
      phone: "021 960 15 57",
      ...ZONE,
      lat: 46.3979,
      lng: 6.9262,
      description: "Boucherie artisanale — viandes suisses.",
      openUntil: "18:00",
      published: true,
      devicePlan: "tablette",
      trialEndsAt,
      emoji: "",
      color: "#C62828",
    },
    {
      id: "shop_visavis",
      name: "Vis-à-Vis Alimentation",
      slug: "vis-a-vis",
      category: "epicerie",
      address: "Grand-Rue 31",
      phone: "021 960 12 37",
      ...ZONE,
      lat: 46.3971,
      lng: 6.9254,
      description: "Alimentation générale et produits du quotidien.",
      openUntil: "19:30",
      published: true,
      devicePlan: "telephone",
      trialEndsAt,
      emoji: "",
      color: "#1565C0",
    },
    {
      id: "shop_favrod",
      name: "Boucherie Favrod",
      slug: "favrod",
      category: "autre",
      address: "Grand-Rue 24",
      phone: "021 960 10 64",
      ...ZONE,
      lat: 46.3973,
      lng: 6.9245,
      description: "Les 2 Frères — charcuterie et spécialités.",
      openUntil: "18:00",
      published: false,
      devicePlan: "telephone",
      trialEndsAt,
      emoji: "",
      color: "#8D6E63",
    },
    {
      id: "shop_kiosque",
      name: "Kiosque de la Gare",
      slug: "kiosque-gare",
      category: "kiosque",
      address: "Place de la Gare 1",
      phone: "021 960 44 11",
      ...ZONE,
      lat: 46.3958,
      lng: 6.9272,
      description: "Presse, snacks et boissons près des quais.",
      openUntil: "20:00",
      published: true,
      devicePlan: "telephone",
      trialEndsAt,
      emoji: "",
      color: "#00897B",
    },
    {
      id: "shop_panier",
      name: "Le Panier du Léman",
      slug: "panier-leman",
      category: "epicerie",
      address: "Avenue de la Gare 8",
      phone: "021 960 55 22",
      ...ZONE,
      lat: 46.3962,
      lng: 6.9268,
      description: "Produits régionaux du bord du lac.",
      openUntil: "19:00",
      published: true,
      devicePlan: "tablette",
      trialEndsAt,
      emoji: "",
      color: "#558B2F",
    },
    {
      id: "shop_croissant",
      name: "Au Croissant Doré",
      slug: "croissant-dore",
      category: "boulangerie",
      address: "Rue du Lac 15",
      phone: "021 960 33 01",
      ...ZONE,
      lat: 46.3982,
      lng: 6.9242,
      description: "Boulangerie artisanale face au lac.",
      openUntil: "18:00",
      published: true,
      devicePlan: "telephone",
      trialEndsAt,
      emoji: "",
      color: "#EF6C00",
    },
  ];
}

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600_000).toISOString();
}

function minutesAgo(m: number): string {
  return new Date(Date.now() - m * 60_000).toISOString();
}

export function createSeedOffers(shops: Shop[]): Offer[] {
  const end = (shopId: string) => {
    const shop = shops.find((s) => s.id === shopId)!;
    return todayEndOfDayISO(shop.openUntil);
  };

  return [
    {
      id: "offer_mangues",
      shopId: "shop_dasilva",
      title: "Mangues mûres à point",
      description:
        "Lot de mangues parfaitement mûres — idéales pour aujourd'hui. Qualité premium, prix flash.",
      type: "FLASH",
      status: "PUBLIEE",
      price: 4.9,
      originalPrice: 7.9,
      quantityTotal: 12,
      quantityLeft: 7,
      unit: "lot",
      emoji: "",
      validUntil: end("shop_dasilva"),
      createdAt: hoursAgo(3),
      publishedAt: hoursAgo(3),
      views: 86,
    },
    {
      id: "offer_pain",
      shopId: "shop_durgnat",
      title: "Pain au levain du jour",
      description:
        "Pains au levain sortis ce matin. À retirer avant fermeture — croûte dorée garantie.",
      type: "ARRIVAGE",
      status: "PUBLIEE",
      price: 3.5,
      quantityTotal: 20,
      quantityLeft: 14,
      unit: "pièce",
      emoji: "",
      validUntil: end("shop_durgnat"),
      createdAt: hoursAgo(5),
      publishedAt: hoursAgo(5),
      views: 124,
    },
    {
      id: "offer_fromage",
      shopId: "shop_macheret",
      title: "Tomme vaudoise -20%",
      description:
        "Tomme locale affinées — promo du jour. Parfaite pour un apéro lémanique.",
      type: "PROMO",
      status: "PUBLIEE",
      price: 8.0,
      originalPrice: 10.0,
      quantityTotal: 8,
      quantityLeft: 5,
      unit: "pièce",
      emoji: "",
      validUntil: end("shop_macheret"),
      createdAt: hoursAgo(2),
      publishedAt: hoursAgo(2),
      views: 67,
    },
    {
      id: "offer_vrac",
      shopId: "shop_vracshop",
      title: "Fruits secs en vrac",
      description:
        "Mélange fruits secs bio — apportez votre sachet ou utilisez le nôtre.",
      type: "PROMO",
      status: "PUBLIEE",
      price: 6.5,
      originalPrice: 8.5,
      quantityTotal: 15,
      quantityLeft: 11,
      unit: "500g",
      emoji: "",
      validUntil: end("shop_vracshop"),
      createdAt: hoursAgo(4),
      publishedAt: hoursAgo(4),
      views: 52,
    },
    {
      id: "offer_steak",
      shopId: "shop_fontaine",
      title: "Entrecôtes suisses",
      description:
        "Dernières entrecôtes du jour — à saisir avant 18h. Viande locale.",
      type: "DERNIERE_MINUTE",
      status: "PUBLIEE",
      price: 18.9,
      originalPrice: 24.9,
      quantityTotal: 6,
      quantityLeft: 3,
      unit: "lot",
      emoji: "",
      validUntil: end("shop_fontaine"),
      createdAt: hoursAgo(1),
      publishedAt: hoursAgo(1),
      views: 41,
    },
    {
      id: "offer_croissants",
      shopId: "shop_croissant",
      title: "Croissants du soir",
      description:
        "Lot de 4 croissants au beurre — dernière heure avant fermeture.",
      type: "DERNIERE_MINUTE",
      status: "PUBLIEE",
      price: 4.0,
      originalPrice: 6.4,
      quantityTotal: 10,
      quantityLeft: 6,
      unit: "lot de 4",
      emoji: "",
      validUntil: end("shop_croissant"),
      createdAt: minutesAgo(45),
      publishedAt: minutesAgo(45),
      views: 38,
    },
    {
      id: "offer_legumes",
      shopId: "shop_panier",
      title: "Panier légumes du Léman",
      description:
        "Assortiment de légumes de saison des producteurs locaux. Fresh du jour.",
      type: "ARRIVAGE",
      status: "PUBLIEE",
      price: 12.0,
      originalPrice: 15.0,
      quantityTotal: 10,
      quantityLeft: 8,
      unit: "panier",
      emoji: "",
      validUntil: end("shop_panier"),
      createdAt: hoursAgo(6),
      publishedAt: hoursAgo(6),
      views: 95,
    },
    {
      id: "offer_snacks",
      shopId: "shop_kiosque",
      title: "Snacks + boisson",
      description: "Combo sandwich + boisson — parfait avant le train.",
      type: "FLASH",
      status: "PUBLIEE",
      price: 7.5,
      originalPrice: 9.5,
      quantityTotal: 15,
      quantityLeft: 9,
      unit: "combo",
      emoji: "",
      validUntil: end("shop_kiosque"),
      createdAt: hoursAgo(2.5),
      publishedAt: hoursAgo(2.5),
      views: 73,
    },
    {
      id: "offer_huile",
      shopId: "shop_visavis",
      title: "Huile d'olive premium",
      description: "Bouteille 75cl en promo — stock limité.",
      type: "PROMO",
      status: "PUBLIEE",
      price: 9.9,
      originalPrice: 14.9,
      quantityTotal: 8,
      quantityLeft: 0,
      unit: "bouteille",
      emoji: "",
      validUntil: end("shop_visavis"),
      createdAt: hoursAgo(8),
      publishedAt: hoursAgo(8),
      views: 110,
    },
    {
      id: "offer_brouillon",
      shopId: "shop_dasilva",
      title: "Bananes bio (brouillon)",
      description: "Offre en préparation — pas encore publiée.",
      type: "PROMO",
      status: "BROUILLON",
      price: 2.5,
      originalPrice: 3.5,
      quantityTotal: 20,
      quantityLeft: 20,
      unit: "kg",
      emoji: "",
      validUntil: end("shop_dasilva"),
      createdAt: hoursAgo(1),
      views: 0,
    },
    {
      id: "offer_saucisson",
      shopId: "shop_favrod",
      title: "Saucisson vaudois",
      description: "Spécialité maison — bientôt en ligne.",
      type: "ARRIVAGE",
      status: "SUSPENDUE",
      price: 11.5,
      quantityTotal: 5,
      quantityLeft: 5,
      unit: "pièce",
      emoji: "",
      validUntil: end("shop_favrod"),
      createdAt: hoursAgo(12),
      views: 4,
    },
  ];
}

export function createSeedReservations(): Reservation[] {
  return [
    {
      id: "resa_1",
      offerId: "offer_mangues",
      shopId: "shop_dasilva",
      clientName: "Marie",
      clientPhone: "079 123 45 67",
      quantity: 2,
      status: "EN_ATTENTE",
      code: "EC-4821",
      message: "Je passe vers 17h",
      createdAt: minutesAgo(12),
      updatedAt: minutesAgo(12),
    },
    {
      id: "resa_2",
      offerId: "offer_pain",
      shopId: "shop_durgnat",
      clientName: "Nico",
      clientPhone: "078 987 65 43",
      quantity: 1,
      status: "CONFIRMEE",
      code: "EC-3104",
      createdAt: hoursAgo(1.5),
      updatedAt: hoursAgo(1.2),
      confirmedAt: hoursAgo(1.2),
    },
    {
      id: "resa_3",
      offerId: "offer_fromage",
      shopId: "shop_macheret",
      clientName: "Sophie",
      clientPhone: "076 555 12 34",
      quantity: 1,
      status: "RECUPEREE",
      code: "EC-2201",
      createdAt: hoursAgo(4),
      updatedAt: hoursAgo(2),
      confirmedAt: hoursAgo(3.5),
      pickedUpAt: hoursAgo(2),
    },
    {
      id: "resa_4",
      offerId: "offer_steak",
      shopId: "shop_fontaine",
      clientName: "Jean",
      clientPhone: "079 444 33 22",
      quantity: 1,
      status: "CONFIRMEE",
      code: "EC-5590",
      createdAt: minutesAgo(40),
      updatedAt: minutesAgo(30),
      confirmedAt: minutesAgo(30),
    },
    {
      id: "resa_5",
      offerId: "offer_croissants",
      shopId: "shop_croissant",
      clientName: "Léa",
      clientPhone: "078 111 22 33",
      quantity: 2,
      status: "REFUSEE",
      code: "EC-7782",
      createdAt: minutesAgo(8),
      updatedAt: minutesAgo(5),
    },
    {
      id: "resa_6",
      offerId: "offer_legumes",
      shopId: "shop_panier",
      clientName: "Pierre",
      clientPhone: "079 888 77 66",
      quantity: 1,
      status: "REFUSEE",
      code: "EC-1099",
      createdAt: hoursAgo(3),
      updatedAt: hoursAgo(2.8),
    },
    {
      id: "resa_7",
      offerId: "offer_snacks",
      shopId: "shop_kiosque",
      clientName: "Camille",
      clientPhone: "076 222 11 00",
      quantity: 1,
      status: "RECUPEREE",
      code: "EC-3344",
      createdAt: hoursAgo(5),
      updatedAt: hoursAgo(4),
      confirmedAt: hoursAgo(4.8),
      pickedUpAt: hoursAgo(4),
    },
    {
      id: "resa_8",
      offerId: "offer_mangues",
      shopId: "shop_dasilva",
      clientName: "Alex",
      clientPhone: "079 000 00 01",
      quantity: 1,
      status: "CONFIRMEE",
      code: "EC-1001",
      createdAt: hoursAgo(2),
      updatedAt: hoursAgo(1.8),
      confirmedAt: hoursAgo(1.8),
    },
    {
      id: "resa_9",
      offerId: "offer_vrac",
      shopId: "shop_vracshop",
      clientName: "Alex",
      clientPhone: "079 000 00 01",
      quantity: 1,
      status: "EN_ATTENTE",
      code: "EC-1002",
      createdAt: minutesAgo(25),
      updatedAt: minutesAgo(25),
    },
  ];
}

export function createSeedAlerts(): Alert[] {
  return [
    {
      id: "alert_1",
      type: "warning",
      title: "No-show potentiel",
      message:
        "2 réservations confirmées chez Da Silva approchent de la fermeture.",
      createdAt: minutesAgo(20),
      shopId: "shop_dasilva",
    },
    {
      id: "alert_2",
      type: "success",
      title: "Nouvelle offre publiée",
      message: "Boulangerie Durgnat a publié « Pain au levain du jour ».",
      createdAt: hoursAgo(5),
      shopId: "shop_durgnat",
    },
    {
      id: "alert_3",
      type: "info",
      title: "Commerce non publié",
      message: "Boucherie Favrod est en liste mais pas encore publiée.",
      createdAt: hoursAgo(10),
      shopId: "shop_favrod",
    },
    {
      id: "alert_4",
      type: "warning",
      title: "Offre épuisée",
      message: "Huile d'olive premium (Vis-à-Vis) est épuisée.",
      createdAt: hoursAgo(1),
      shopId: "shop_visavis",
    },
  ];
}

export function createInitialState(): AppState {
  const shops = createSeedShops();
  const offers = createSeedOffers(shops);
  // Sync quantityLeft with reservations that hold stock
  for (const offer of offers) {
    if (offer.id === "offer_huile") {
      offer.status = "EPUISEE";
      offer.quantityLeft = 0;
    }
  }

  return {
    shops,
    offers,
    reservations: createSeedReservations(),
    favorites: [
      { shopId: "shop_dasilva", addedAt: hoursAgo(48) },
      { shopId: "shop_durgnat", addedAt: hoursAgo(24) },
      { shopId: "shop_macheret", addedAt: hoursAgo(12) },
    ],
    scans: [
      {
        id: "scan_1",
        shopId: "shop_dasilva",
        shopSlug: "da-silva",
        scannedAt: hoursAgo(6),
        sessionId: "sess_a",
        browsed: true,
        reserved: true,
        pickedUp: false,
      },
      {
        id: "scan_2",
        shopId: "shop_dasilva",
        shopSlug: "da-silva",
        scannedAt: hoursAgo(5),
        sessionId: "sess_b",
        browsed: true,
        reserved: false,
        pickedUp: false,
      },
      {
        id: "scan_3",
        shopId: "shop_durgnat",
        shopSlug: "durgnat",
        scannedAt: hoursAgo(4),
        sessionId: "sess_c",
        browsed: true,
        reserved: true,
        pickedUp: true,
      },
      {
        id: "scan_4",
        shopId: "shop_kiosque",
        shopSlug: "kiosque-gare",
        scannedAt: hoursAgo(3),
        sessionId: "sess_d",
        browsed: true,
        reserved: false,
        pickedUp: false,
      },
      {
        id: "scan_5",
        shopId: "shop_macheret",
        shopSlug: "macheret",
        scannedAt: hoursAgo(2),
        sessionId: "sess_e",
        browsed: true,
        reserved: true,
        pickedUp: true,
      },
      {
        id: "scan_6",
        shopId: "shop_fontaine",
        shopSlug: "fontaine",
        scannedAt: hoursAgo(1),
        sessionId: "sess_f",
        browsed: false,
        reserved: false,
        pickedUp: false,
      },
      {
        id: "scan_7",
        shopId: "shop_vracshop",
        shopSlug: "vracshop",
        scannedAt: minutesAgo(30),
        sessionId: "sess_g",
        browsed: true,
        reserved: true,
        pickedUp: false,
      },
      {
        id: "scan_8",
        shopId: "shop_panier",
        shopSlug: "panier-leman",
        scannedAt: minutesAgo(15),
        sessionId: "sess_h",
        browsed: true,
        reserved: false,
        pickedUp: false,
      },
    ],
    presence: [
      {
        sessionId: "live_1",
        lastSeen: minutesAgo(0.2),
        page: "/",
      },
      {
        sessionId: "live_2",
        lastSeen: minutesAgo(0.5),
        page: "/offre/offer_mangues",
      },
      {
        sessionId: "live_3",
        lastSeen: minutesAgo(1),
        page: "/reservations",
      },
      {
        sessionId: "live_4",
        lastSeen: minutesAgo(2),
        page: "/pro",
      },
    ],
    client: {
      id: "client_demo",
      name: "Alex",
      phone: "079 000 00 01",
    },
    alerts: createSeedAlerts(),
    seededAt: new Date().toISOString(),
  };
}
