/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as FondateurRouteImport } from './routes/fondateur'
import { Route as ProRouteImport } from './routes/pro'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppPreferencesRouteImport } from './routes/_app/preferences'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppReservationsRouteImport } from './routes/_app/reservations'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ConfirmationReservationIdRouteImport } from './routes/confirmation.$reservationId'
import { Route as MerchantsMerchantIdRouteImport } from './routes/merchants.$merchantId'
import { Route as OffersOfferIdRouteImport } from './routes/offers.$offerId'
import { Route as ProIndexRouteImport } from './routes/pro/index'
import { Route as ProNewRouteImport } from './routes/pro/new'
import { Route as ProNotificationsRouteImport } from './routes/pro/notifications'
import { Route as ProOffersRouteImport } from './routes/pro/offers'
import { Route as ProOrdersRouteImport } from './routes/pro/orders'
import { Route as ReservationsReservationIdRouteImport } from './routes/reservations.$reservationId'
import { Route as ReserveOfferIdRouteImport } from './routes/reserve.$offerId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const FondateurRoute = FondateurRouteImport.update({
  id: '/fondateur',
  path: '/fondateur',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferencesRoute = AppPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ConfirmationReservationIdRoute =
  ConfirmationReservationIdRouteImport.update({
    id: '/confirmation/$reservationId',
    path: '/confirmation/$reservationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantsMerchantIdRoute = MerchantsMerchantIdRouteImport.update({
  id: '/merchants/$merchantId',
  path: '/merchants/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersOfferIdRoute = OffersOfferIdRouteImport.update({
  id: '/offers/$offerId',
  path: '/offers/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const ProNewRoute = ProNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProRoute,
} as any)
const ProNotificationsRoute = ProNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProRoute,
} as any)
const ProOffersRoute = ProOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => ProRoute,
} as any)
const ProOrdersRoute = ProOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProRoute,
} as any)
const ReservationsReservationIdRoute =
  ReservationsReservationIdRouteImport.update({
    id: '/reservations/$reservationId',
    path: '/reservations/$reservationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReserveOfferIdRoute = ReserveOfferIdRouteImport.update({
  id: '/reserve/$offerId',
  path: '/reserve/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/fondateur': typeof FondateurRoute
  '/pro': typeof ProRouteWithChildren
  '/search': typeof SearchRoute
  '/explore': typeof AppExploreRoute
  '/favorites': typeof AppFavoritesRoute
  '/help': typeof AppHelpRoute
  '/preferences': typeof AppPreferencesRoute
  '/profile': typeof AppProfileRoute
  '/reservations': typeof AppReservationsRoute
  '/settings': typeof AppSettingsRoute
  '/confirmation/$reservationId': typeof ConfirmationReservationIdRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/pro/new': typeof ProNewRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/offers': typeof ProOffersRoute
  '/pro/orders': typeof ProOrdersRoute
  '/reservations/$reservationId': typeof ReservationsReservationIdRoute
  '/reserve/$offerId': typeof ReserveOfferIdRoute
  '/pro/': typeof ProIndexRoute
}
export interface FileRoutesByTo {
  '/fondateur': typeof FondateurRoute
  '/search': typeof SearchRoute
  '/explore': typeof AppExploreRoute
  '/favorites': typeof AppFavoritesRoute
  '/help': typeof AppHelpRoute
  '/preferences': typeof AppPreferencesRoute
  '/profile': typeof AppProfileRoute
  '/reservations': typeof AppReservationsRoute
  '/settings': typeof AppSettingsRoute
  '/confirmation/$reservationId': typeof ConfirmationReservationIdRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/pro/new': typeof ProNewRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/offers': typeof ProOffersRoute
  '/pro/orders': typeof ProOrdersRoute
  '/reservations/$reservationId': typeof ReservationsReservationIdRoute
  '/reserve/$offerId': typeof ReserveOfferIdRoute
  '/': typeof AppIndexRoute
  '/pro': typeof ProIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/fondateur': typeof FondateurRoute
  '/pro': typeof ProRouteWithChildren
  '/search': typeof SearchRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/preferences': typeof AppPreferencesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reservations': typeof AppReservationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/confirmation/$reservationId': typeof ConfirmationReservationIdRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/pro/new': typeof ProNewRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/offers': typeof ProOffersRoute
  '/pro/orders': typeof ProOrdersRoute
  '/reservations/$reservationId': typeof ReservationsReservationIdRoute
  '/reserve/$offerId': typeof ReserveOfferIdRoute
  '/_app/': typeof AppIndexRoute
  '/pro/': typeof ProIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fondateur'
    | '/pro'
    | '/search'
    | '/explore'
    | '/favorites'
    | '/help'
    | '/preferences'
    | '/profile'
    | '/reservations'
    | '/settings'
    | '/confirmation/$reservationId'
    | '/merchants/$merchantId'
    | '/offers/$offerId'
    | '/pro/new'
    | '/pro/notifications'
    | '/pro/offers'
    | '/pro/orders'
    | '/reservations/$reservationId'
    | '/reserve/$offerId'
    | '/pro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fondateur'
    | '/search'
    | '/explore'
    | '/favorites'
    | '/help'
    | '/preferences'
    | '/profile'
    | '/reservations'
    | '/settings'
    | '/confirmation/$reservationId'
    | '/merchants/$merchantId'
    | '/offers/$offerId'
    | '/pro/new'
    | '/pro/notifications'
    | '/pro/offers'
    | '/pro/orders'
    | '/reservations/$reservationId'
    | '/reserve/$offerId'
    | '/'
    | '/pro'
  id:
    | '__root__'
    | '/_app'
    | '/fondateur'
    | '/pro'
    | '/search'
    | '/_app/explore'
    | '/_app/favorites'
    | '/_app/help'
    | '/_app/preferences'
    | '/_app/profile'
    | '/_app/reservations'
    | '/_app/settings'
    | '/confirmation/$reservationId'
    | '/merchants/$merchantId'
    | '/offers/$offerId'
    | '/pro/new'
    | '/pro/notifications'
    | '/pro/offers'
    | '/pro/orders'
    | '/reservations/$reservationId'
    | '/reserve/$offerId'
    | '/_app/'
    | '/pro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  FondateurRoute: typeof FondateurRoute
  ProRoute: typeof ProRouteWithChildren
  SearchRoute: typeof SearchRoute
  ConfirmationReservationIdRoute: typeof ConfirmationReservationIdRoute
  MerchantsMerchantIdRoute: typeof MerchantsMerchantIdRoute
  OffersOfferIdRoute: typeof OffersOfferIdRoute
  ReservationsReservationIdRoute: typeof ReservationsReservationIdRoute
  ReserveOfferIdRoute: typeof ReserveOfferIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fondateur': {
      id: '/fondateur'
      path: '/fondateur'
      fullPath: '/fondateur'
      preLoaderRoute: typeof FondateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preferences': {
      id: '/_app/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AppPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/confirmation/$reservationId': {
      id: '/confirmation/$reservationId'
      path: '/confirmation/$reservationId'
      fullPath: '/confirmation/$reservationId'
      preLoaderRoute: typeof ConfirmationReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/$merchantId': {
      id: '/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof MerchantsMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$offerId': {
      id: '/offers/$offerId'
      path: '/offers/$offerId'
      fullPath: '/offers/$offerId'
      preLoaderRoute: typeof OffersOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/new': {
      id: '/pro/new'
      path: '/new'
      fullPath: '/pro/new'
      preLoaderRoute: typeof ProNewRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/notifications': {
      id: '/pro/notifications'
      path: '/notifications'
      fullPath: '/pro/notifications'
      preLoaderRoute: typeof ProNotificationsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/offers': {
      id: '/pro/offers'
      path: '/offers'
      fullPath: '/pro/offers'
      preLoaderRoute: typeof ProOffersRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/orders': {
      id: '/pro/orders'
      path: '/orders'
      fullPath: '/pro/orders'
      preLoaderRoute: typeof ProOrdersRouteImport
      parentRoute: typeof ProRoute
    }
    '/reservations/$reservationId': {
      id: '/reservations/$reservationId'
      path: '/reservations/$reservationId'
      fullPath: '/reservations/$reservationId'
      preLoaderRoute: typeof ReservationsReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/$offerId': {
      id: '/reserve/$offerId'
      path: '/reserve/$offerId'
      fullPath: '/reserve/$offerId'
      preLoaderRoute: typeof ReserveOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppPreferencesRoute: typeof AppPreferencesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHelpRoute: AppHelpRoute,
  AppPreferencesRoute: AppPreferencesRoute,
  AppProfileRoute: AppProfileRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProRouteChildren {
  ProNewRoute: typeof ProNewRoute
  ProNotificationsRoute: typeof ProNotificationsRoute
  ProOffersRoute: typeof ProOffersRoute
  ProOrdersRoute: typeof ProOrdersRoute
  ProIndexRoute: typeof ProIndexRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProNewRoute: ProNewRoute,
  ProNotificationsRoute: ProNotificationsRoute,
  ProOffersRoute: ProOffersRoute,
  ProOrdersRoute: ProOrdersRoute,
  ProIndexRoute: ProIndexRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  FondateurRoute: FondateurRoute,
  ProRoute: ProRouteWithChildren,
  SearchRoute: SearchRoute,
  ConfirmationReservationIdRoute: ConfirmationReservationIdRoute,
  MerchantsMerchantIdRoute: MerchantsMerchantIdRoute,
  OffersOfferIdRoute: OffersOfferIdRoute,
  ReservationsReservationIdRoute: ReservationsReservationIdRoute,
  ReserveOfferIdRoute: ReserveOfferIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
