/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProRouteImport } from './routes/pro'
import { Route as ProIndexRouteImport } from './routes/pro/index'
import { Route as ProNewRouteImport } from './routes/pro/new'
import { Route as ProNotificationsRouteImport } from './routes/pro/notifications'
import { Route as ProOffersRouteImport } from './routes/pro/offers'
import { Route as ProOrdersRouteImport } from './routes/pro/orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const ProNewRoute = ProNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProRoute,
} as any)
const ProNotificationsRoute = ProNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProRoute,
} as any)
const ProOffersRoute = ProOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => ProRoute,
} as any)
const ProOrdersRoute = ProOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pro': typeof ProRouteWithChildren
  '/pro/new': typeof ProNewRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/offers': typeof ProOffersRoute
  '/pro/orders': typeof ProOrdersRoute
  '/pro/': typeof ProIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pro/new': typeof ProNewRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/offers': typeof ProOffersRoute
  '/pro/orders': typeof ProOrdersRoute
  '/pro': typeof ProIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pro': typeof ProRouteWithChildren
  '/pro/new': typeof ProNewRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/offers': typeof ProOffersRoute
  '/pro/orders': typeof ProOrdersRoute
  '/pro/': typeof ProIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pro'
    | '/pro/new'
    | '/pro/notifications'
    | '/pro/offers'
    | '/pro/orders'
    | '/pro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pro/new'
    | '/pro/notifications'
    | '/pro/offers'
    | '/pro/orders'
    | '/pro'
  id:
    | '__root__'
    | '/'
    | '/pro'
    | '/pro/new'
    | '/pro/notifications'
    | '/pro/offers'
    | '/pro/orders'
    | '/pro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProRoute: typeof ProRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/new': {
      id: '/pro/new'
      path: '/new'
      fullPath: '/pro/new'
      preLoaderRoute: typeof ProNewRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/notifications': {
      id: '/pro/notifications'
      path: '/notifications'
      fullPath: '/pro/notifications'
      preLoaderRoute: typeof ProNotificationsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/offers': {
      id: '/pro/offers'
      path: '/offers'
      fullPath: '/pro/offers'
      preLoaderRoute: typeof ProOffersRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/orders': {
      id: '/pro/orders'
      path: '/orders'
      fullPath: '/pro/orders'
      preLoaderRoute: typeof ProOrdersRouteImport
      parentRoute: typeof ProRoute
    }
  }
}

interface ProRouteChildren {
  ProNewRoute: typeof ProNewRoute
  ProNotificationsRoute: typeof ProNotificationsRoute
  ProOffersRoute: typeof ProOffersRoute
  ProOrdersRoute: typeof ProOrdersRoute
  ProIndexRoute: typeof ProIndexRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProNewRoute: ProNewRoute,
  ProNotificationsRoute: ProNotificationsRoute,
  ProOffersRoute: ProOffersRoute,
  ProOrdersRoute: ProOrdersRoute,
  ProIndexRoute: ProIndexRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProRoute: ProRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
